### ISSUE TITLE
[FEATURE] KoP transaction M2

### ISSUE THREAD

**Issue by gaoran10** [streamnative/kop#310]
The KoP transaction milestone2 tasks.

## Tasks

- [ ] Transaction Coordinator
  - [ ] generate pid
  - [ ] zombie client fence
  - [ ] transaction log
- [ ] Consumer Coordinator
  - [ ] transaction offset commit
  - [ ] write transaction marker
- [ ] Topic Partition Leader Broker
  - [ ] aborted index log
- [ ] Test
  - [ ] Kafka client test migrate

**Comment by gaoran10** [comment]
Use this [Epic] (https://app.zenhub.com/workspaces/platform---messaging-5fc70118922dc1000e323fa2/issues/streamnative/platform-epics/213) to track the KoP transaction tasks in M2, I closed this issue.
