### ISSUE TITLE
[FEATURE] Add transaction support

### ISSUE THREAD

**Issue by jiazhai** [streamnative/kop#39]
RFC: streamnative/community#2

## Tasks

- [x] Transaction Coordinator
  - [x] producer id manager #372
  - [x] producer fence
  - [x] transaction metadata #295 
  - [x] add partitions to transaction #295 
  - [x] end transaction #295 
  - [x] transcation marker channel handler #295 
  - [x] transaction log
- [x] Consumer Coordinator
  - [x] transaction offset commit #365
  - [x] write transaction marker #365
- [ ] Topic Partition Leader Broker
  - [x] find transaction coordinator #295 
  - [x] send transaction message #295 
  - [x] write transaction marker #295 
  - [x] read isolation #295 
  - [ ] aborted index log
- [ ] Metrics
- [ ] Test
  - [x] basic produce transaction messages and consume test (read_committed, read_uncommitted) #295
  - [ ] Kafka client test migrate

**Comment by zhaohaidao** [comment]
Hi @gaoran10 Is there any unassigned issue which I would like to pick up.

**Comment by gaoran10** [comment]
> Hi @gaoran10 Is there any unassigned issue which I would like to pick up.

I'm working on processing the producer state snapshot and recovery. Could you help check that is there any more transaction tests in Kafka? Migrate them to KoP first if exists.

I think there are many codes that need to refine, if you find anything about the transaction need to do, you could open an issue to track the task, and this will help us to sync status. Thanks.
