### ISSUE TITLE
[FEATURE] Transaction task list

### ISSUE THREAD

**Issue by gaoran10** [streamnative/kop#728]
#  Transaction Tasks

- [ ] Transaction log https://github.com/streamnative/kop/pull/424, https://github.com/streamnative/kop/pull/430
- [ ] Transaction state manager https://github.com/streamnative/kop/pull/450
- [ ] Transaction state manager snapshot & recovery
- [ ] Transaction timeout
- [ ] Imigrate Kafka transaction test (WIP)
- [ ] Transaction coordinator fence
- [ ] Transaction metric
- [ ] Transaction performance test
