### ISSUE TITLE
[FEATURE] The remains of authorization support task list

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#759]
## Background
After #236, there are still have some unauthorized requests were left behind, most of them are admin operations. 
This is a list of tasks left over.

## Task List

- [x] Add authorization to CREATE_TOPICS (#758)
- [x] Add authorization to DELETE_TOPICS (#758)
- [x] Add authorization to OFFSET_COMMIT (#762)
- [x] Add authorization to ADD_PARTITIONS_TO_TXN (#782)
- [x] Add authorization to TXN_OFFSET_COMMIT (#801)
- [x] Add authorization to DESCRIBE_CONFIGS (#774)
