### ISSUE TITLE
Migrate transaction coordinator tests

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#897]
## Background / Description

Currently, KoP support transaction but don't have units test to cover transaction coordinator code behavior, for future maintain, we should add units test from Kafka.

## Definition of done
- [x] Migrate transaction coordinator handleInitProducerId tests(#875 , #890)
- [x] Migrate transaction coordinator handleAddPartitionsToTransaction tests(#885 )
- [x] Migrate transaction coordinator handleEndTransaction tests(#887 )
- [x] Migrate transaction coordinator emigration tests(#905 )
